### ISSUE TITLE
consider using https://github.com/containers/ocidir-rs

### ISSUE THREAD

**Issue by tofay** [microsoft/rpmoci#132]
I noticed that crate has been spun out of https://github.com/ostreedev/ostree-rs-ext/

**Comment by cgwalters** [comment]
Also worth noting that it would also tend to imply using https://docs.rs/oci-spec/latest/oci_spec/ vs https://github.com/microsoft/rpmoci/blob/main/src/config.rs right?

**Comment by cgwalters** [comment]
(Nevermind the previous comment)

Yep, happy to help if you run into any issues!
